services:
    app:
        build:
            context: .
        container_name: python_backend
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - default
        volumes:
            - .:/app

    db:
        image: postgres:15
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5433:${POSTGRES_PORT}"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - default

    llama-edge-api-server:
        build:
            context: .
            dockerfile: model.Dockerfile
        container_name: api_server
        ports:
            - "8080:8080"
        networks:
            - default

volumes:
    postgres_data:
